const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
const SIGNOUT_ERROR = 'LOGOUT_ERROR';
const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

const authTypes = {
  LOGIN_ERROR,
  LOGIN_SUCCESS,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  SIGNOUT_ERROR,
  SIGNOUT_SUCCESS
}

export default authTypes;